services:
  - type: web
    name: Vision-Insight-api
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend/api && uvicorn api:app --host 0.0.0.0 --port $PORT